### ISSUE TITLE
WAT tests and exporting

### ISSUE THREAD

**Issue by isokissa** [AlexDarigan/WAT-GDScript#194]
Please explain how does export of the game work if there are WAT assets and my unit tests. They are not needed in production, but how to exclude them from export, when generating the executable? 

thanks in advance

**Comment by AlexDarigan** [comment]
No major features for this (yet). There are two workarounds. 

1) Just delete the folder. I think you may also be able to add flag to your project exports to ignore your test folder

2) Store your tests outside of your project repo.

i.e

- Project
-- Tests
-- GodotProject

(When scripts are loaded into Godot from outside, they consider themselves to be in the "res://" part of the folder in case of relative filenames).

**Comment by Boivin92** [comment]
In your export configs you can create a rule to ignore your test folder. Take a look at the bottom-right text-box

![image](https://user-images.githubusercontent.com/8545474/115918409-7c4c3580-a445-11eb-9ee1-234636f39d8f.png)

**Comment by AlexDarigan** [comment]
Since Godot can handle this, I'm going to close this issue.
