### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by SimonasLetukas** [AlexDarigan/WAT-GDScript#198]
Hello,

Has anyone else had problems with tests not appearing in the Tests tab? I tried following https://wat.readthedocs.io/en/latest/pages/getting_started/introduction.html and copy pasting the code, but it does not seem to work. Hopefully you could guide me to the right direction! Thanks :)

![image](https://user-images.githubusercontent.com/4127189/108759184-b340c080-7554-11eb-9b2d-52309e2bfefa.png)

**Comment by AlexDarigan** [comment]
Reload the Plugin with tests in directory and see what happens.

Failing that, try turning on the auto refresh setting in the wat project settings.

**Comment by SimonasLetukas** [comment]
Tried both and still can't see anything. The output has quite a number of errors, not sure if they intended:

`
 res://addons/WAT/core/test_runner/test_runner.gd:24 - Parse Error: The assigned value's type (client.gd) doesn't match the variable's type (Client.gd).
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/ui/scripts/GUI.gd:8 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 modules/gdscript/gdscript_functions.cpp:817 - You may change any setting for WAT in Project -> ProjectSettings -> General -> WAT
 res://addons/WAT/core/test_runner/test_runner.gd:24 - Parse Error: The assigned value's type (client.gd) doesn't match the variable's type (Client.gd).
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/plugin.gd:27 - Invalid get index 'TestMenu' (on base: 'PanelContainer (GUI.gd)').
`

**Comment by AlexDarigan** [comment]
Could you compare this against the master branch and see if there's any chance?

**Comment by AlexDarigan** [comment]
Assuming this is running fine in master?

**Comment by SimonasLetukas** [comment]
Haven't tried yet, will come back with info once I try it (and close this thread if it works).

**Comment by SimonasLetukas** [comment]
Tried with the files in master, seems like it does not load correctly:
![image](https://user-images.githubusercontent.com/4127189/109381882-9c4bf680-78e5-11eb-9c88-208a66013a16.png)

**Comment by AlexDarigan** [comment]
Could you show me the very first part of that output?

I have no idea what's going on.

**Comment by SimonasLetukas** [comment]
This is the whole output when I enable the plugin:
```
 res://addons/WAT/core/assertions/string.gd:53 - Parse Error: The identifier "string" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/assertions/assertions.gd:12 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test/test.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test_runner/test_controller.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test_runner/single_threaded_runner.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test_runner/test_runner.gd:5 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/ui/scripts/gui.gd:8 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 modules/gdscript/gdscript_functions.cpp:817 - You may change any setting for WAT in Project -> ProjectSettings -> General -> WAT
 res://addons/WAT/core/assertions/string.gd:53 - Parse Error: The identifier "string" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/assertions/assertions.gd:12 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test/test.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test_runner/test_controller.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test_runner/single_threaded_runner.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test_runner/test_runner.gd:5 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/assertions/string.gd:53 - Parse Error: The identifier "string" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/assertions/assertions.gd:12 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/core/test/test.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/namespace.gd:4 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://tests/client_map.test.gd:1 - Parse Error: Couldn't find the subclass: WAT.Test
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/plugin.gd:27 - Invalid get index 'TestMenu' (on base: 'PanelContainer (gui.gd)').
```

**Comment by AlexDarigan** [comment]
This was my bad. I pushed 2 incomplete features where I forgot to correct the names. 54d34f7fdae63f52aae0029fdc7f6647af47a00b should work.

**Comment by SimonasLetukas** [comment]
That fixed the issue -- most of the errors are gone. The only one that remains:
```
res://addons/WAT/plugin.gd:27 - Invalid get index 'TestMenu' (on base: 'PanelContainer (gui.gd)').
```

Still, nothing happens when I press "Run All" and the test window does not show any tests nor their outcomes. Curiously though, I am able to navigate and see my test scripts when pressing on `Select Test -> res://tests`.

**Comment by AlexDarigan** [comment]
Might be a race condition when setting up the window. I decided to make the window earlier but this is ultimately a guess. See what you get from 7832ef89675c70ddc9bd4703421d363527d754b0.

**Comment by SimonasLetukas** [comment]
I see no change. Also I can see more errors upon opening the project (the errors before appeared when I switched "enabled" off and on): 
```
 res://addons/WAT/core/test_runner/test_runner.gd:24 - Parse Error: The assigned value's type (client.gd) doesn't match the variable's type (Client.gd).
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/ui/scripts/gui.gd:8 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
 modules/gdscript/gdscript_functions.cpp:817 - You may change any setting for WAT in Project -> ProjectSettings -> General -> WAT
 res://addons/WAT/core/test_runner/test_runner.gd:24 - Parse Error: The assigned value's type (client.gd) doesn't match the variable's type (Client.gd).
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
Switch Scene Tab
 res://addons/WAT/plugin.gd:27 - Invalid get index 'TestMenu' (on base: 'PanelContainer (gui.gd)').
```

I can see same error as before on the same line, unfortunately... :(

**Comment by AlexDarigan** [comment]
Can you make a very minimal version of this and upload it so I can check against that.

**Comment by AlexDarigan** [comment]
Actually do you have a class that uses the class_name "Client"? I think this could be a name conflict.

Maybe b1f2f1b06bcbf3069811c1c0834b0ceea9f60816 ?

**Comment by SimonasLetukas** [comment]
Yes, I do have such class :D

**Comment by SimonasLetukas** [comment]
I removed Server type from res://addons/WAT/ui/scripts/gui.gd and the tests started working. Seems the issue was with my project using the same types as the plugin. Maybe there is a way to scope the types to only be used in WAT's namespace? Not really sure how that would work on GDScript. Or maybe it would be best not to have any typed variables in the WAT's scripts? 

Only my two cents. Anyway, really happy this works now, will start working on unit testing my project :) 

Thanks so much for the help and attention!

**Comment by AlexDarigan** [comment]
Trust me I've tried but I can't because a namespace ends up requiring cyclic references. Good to know it works.

You might be right about removing types (or making the checks manual). Removed types would also me to support 3.1.
