### ISSUE TITLE
asserts.that requires passed and failed strings to use all method arguments

### ISSUE THREAD

**Issue by AnmAtAnm** [AlexDarigan/WAT-GDScript#199]
Passing all method arguments directly into `passed` or `failed` strings means that if either string does not have the formatting to consume the arguments (or the object itself), the test process crashes with the following error:

```
not all arguments converted during string formatting in operator '%'.
```

Example:
```gdscript
asserts.that(array, "empty", [], "Array is empty", "Empty", "Found %s items" % array.size())
```

Neither `passed` nor `failed` use the format arguments.

**Comment by AlexDarigan** [comment]
I'll need to take a look at this but it might be a while.

**Comment by AlexDarigan** [comment]
I really was a while.

Arrays won't work with assert that (callv can't be invoked on virtual classes) anyway only objects.

I removed the weird formatting I was doing so now it just takes everything raw and outputs it fairly raw in d3d228fc3e5f974a59e2f1a2ced07f3c322f9909
