### ISSUE TITLE
Add asserts.is_empty(arrayOrString, context)

### ISSUE THREAD

**Issue by AnmAtAnm** [AlexDarigan/WAT-GDScript#201]
Add an assert method to check an array or string for emptiness, that outputs the contents of the array/string if it is not empty as part of the `result` message.

**Comment by AlexDarigan** [comment]
Added this in 5aa3cb3989c7bf56ec4788c933dd2416bf0a8035. Hopefully it works. Should be valid for dictionaries too.

**Comment by AlexDarigan** [comment]
Closing since it is added.
