### ISSUE TITLE
A stubbed _ready does not seem to be called when adding the mocked node to the tree

### ISSUE THREAD

**Issue by ChocolatePinecone** [AlexDarigan/WAT-GDScript#203]
The following code does not call the stubbed version of _ready, but calls the real one:
![image](https://user-images.githubusercontent.com/25863930/109715041-69cf2180-7ba3-11eb-85be-4eee59fc4873.png)

When calling _ready manually on the double it does trigger correctly.

**Comment by AlexDarigan** [comment]
_ready, _enter_tree, _exit_tree, _process & _process_delta are special virtual methods. They can't (and probably shouldn't) be dummied/stubbed. The calls to them are done recursively by the engine so I don't have any control over them. I'll add a warning though.

**Comment by ChocolatePinecone** [comment]
I see. I ran into this when creating a test that uses a secondary object that needed to be added into the tree.
This then automatically triggered the secondary object's ready function with side effects that I'm not interested in for the respective test.
In this case, stubbing would be great, but I understand it's not possible/simple to set up.
