### ISSUE TITLE
WAT No Longer runs automatically on Linux in Godot 3.2.4RC3

### ISSUE THREAD

**Issue by FeralBytes** [AlexDarigan/WAT-GDScript#204]
--Is it because I am running a Mono version of Godot?-- Nope I tried the none Mono version and same thing. It just never launches the Test runner scene.
![Peek 2021-03-02 18-49](https://user-images.githubusercontent.com/7874274/109750089-45b21700-7b88-11eb-986f-a0225afe1a84.gif)

Also I encountered a error while recording the above. It only happened 1 time and not when I tried again. But in case you want to see the output.
![Peek 2021-03-02 18-47](https://user-images.githubusercontent.com/7874274/109750146-5f535e80-7b88-11eb-97dc-a6ef8b52d615.gif)

**Comment by AlexDarigan** [comment]
Hmm. I can see all of your tests are in subdirs of the main test folder. I wonder if WAT is reading that as "no tests"? There should be an error about it. Try making a test with at least one testcase as an immediate child of the main test and see what happens.

**Comment by FeralBytes** [comment]
I made a test in the top directory but WAT still fails to run, unless I manually run the scene.
![Peek 2021-03-04 14-07](https://user-images.githubusercontent.com/7874274/110042971-0d7b1780-7cf3-11eb-842f-92ec437ad318.gif)

**Comment by AlexDarigan** [comment]
You have 40 warnings. Are any of those from WAT?

I'll check this myself during the weekend.

**Comment by FeralBytes** [comment]
I looked through all of the Warnings and none of them are from WAT.

**Comment by AlexDarigan** [comment]
Are you able to replicate this with a single test in an isolated project? 

Also I see you're tests are referring to ECS, are you by any chance using GoDex because I'm not sure if WAT will work with that.

**Comment by FeralBytes** [comment]
I will setup a test in an isolated project in a day or so and report back. 

The ECS that I am using is custom written, it is not using GODEX. 

No problem, I can wait college is much more important. Besides the workaround of running the custom scene does still work. Good luck with your classes.

**Comment by AlexDarigan** [comment]
* First appearance of this bug was Beta 6
* It exists in both Windows and Linux builds.

**Comment by AlexDarigan** [comment]
Should be resolved by b796a8fc7e47530b8c37567be78cf630266cdd16

It was a bad if check.

**Comment by FeralBytes** [comment]
This is a clean project with nothing installed in Godot 3.2.4-RC4. Installing the plugin is fine, but enabling it results in the following.
```
 modules/gdscript/gdscript.cpp:813 - Condition "err" is true. Returned: err
 Cannot load source code from file 'res://addons/WAT/ui/scripts/GUI.gd'.
 Failed loading resource: res://addons/WAT/ui/scripts/GUI.gd. Make sure resources have been imported by opening the project in the editor at least once.
 modules/gdscript/gdscript.cpp:813 - Condition "err" is true. Returned: err
 Cannot load source code from file 'res://addons/WAT/ui/scripts/GUI.gd'.
 Failed loading resource: res://addons/WAT/ui/scripts/GUI.gd. Make sure resources have been imported by opening the project in the editor at least once.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/WAT/ui/scripts/GUI.gd
 modules/gdscript/gdscript_functions.cpp:817 - You may change any setting for WAT in Project -> ProjectSettings -> General -> WAT
 modules/gdscript/gdscript_functions.cpp:817 - 7
 modules/gdscript/gdscript_functions.cpp:803 - res://tests : 31 
 modules/gdscript/gdscript_functions.cpp:817 - 7
 In Object of type 'PanelContainer': Attempt to connect nonexistent signal 'launched_via_editor' to method 'EditorPlugin._on_launched_via_editor'.
 In Object of type 'PanelContainer': Attempt to connect nonexistent signal 'function_selected' to method 'EditorPlugin._on_function_selected'.
 res://addons/WAT/plugin.gd:27 - Invalid get index 'TestMenu' (on base: 'PanelContainer').
```
Trying to run the tests, it does not make the "tests" directory.
```
 modules/gdscript/gdscript_functions.cpp:817 - 7
 File must be opened before use.
 modules/gdscript/gdscript_functions.cpp:803 - res://tests : 31 
 modules/gdscript/gdscript_functions.cpp:817 - 7
 res://addons/WAT/ui/scripts/test_menu.gd:109 - Invalid get index 'res://tests' (on base: 'Dictionary').
```
And now I could not get it to run the tests at all.
Minimum Project: 
[WATTest.tar.gz](https://github.com/AlexDarigan/WAT-GDScript/files/6135757/WATTest.tar.gz)
Sorry you might be on Windows: 
[WATTest.zip](https://github.com/AlexDarigan/WAT-GDScript/files/6135759/WATTest.zip)

**Comment by FeralBytes** [comment]
Latest Master fixes the issue. Thank you.
