### ISSUE TITLE
Incorrect capitalisation of GUI.gd - breaks 5.0 on Linux

### ISSUE THREAD

**Issue by mattgorle** [AlexDarigan/WAT-GDScript#207]
WAT 5.0 is broken on Linux.  This is in its vanilla form, as installed from Asset Store.

The problem is caused by case sensitivity.  

addons/WAT/gui.tscn, line 3: `[ext_resource path="res://addons/WAT/ui/scripts/GUI.gd" type="Script" id=1]`

The file on the disk is called addons/WAT/ui/scripts/gui.gd.  This will never resolve on a case-sensitive file system.

I fixed it by renaming addons/WAT/ui/scripts/gui.gd to addons/WAT/ui/scripts/GUI, but the more sensible option is probably to change the reference in addons/WAT/gui.tscn.

Happy to create a pull request if that will help

**Comment by AlexDarigan** [comment]
A PR would be good.

It's bit of an issue with how git handles case sensitivity as well, you need to essentially remove or name it to something else entirely, then rename it back to the proper form. It is one that keeps coming and going.

**Comment by mattgorle** [comment]
Interestingly, it looks like this has already been fixed on the master branch.  The bug is there at the `v5.0.0` tag, but has been corrected at the current head.

I guess this will just roll into the next release!  :-)

**Comment by AlexDarigan** [comment]
Resolved in master. Closing this since release is soon.
