### ISSUE TITLE
Order of Tests for State Machine

### ISSUE THREAD

**Issue by FeralBytes** [AlexDarigan/WAT-GDScript#208]
@AlexDarigan I was wondering is there a way to ensure the order of the tests? I realize this is outside the realm of unit testing. But I would also like to conduct some integration tests. But it seems that the order that the test are written does not guarantee there order in WAT. I also see this is likely so that multi-threading can be applied. But is it possible? Should I be thinking in a different manner? Do I need to write one really long test for the state machine? This state machine controls the flow of my program. Thank you for your time.

**Comment by AlexDarigan** [comment]
It is typically considered a bad idea to have tests be order dependent. It is important for tests to be isolated from each other so a bad test doesn't end up corrupting a good test. (i.e. it is easier to see a problem when 1 test fails and 1 test passes then when both tests fail). Some frameworks like JUnit take this to the extreme where they will create a whole new class before a test method is run.

A State Machine seems like a thing where you should be able to do a suite of tests easily enough. You have it start in one state, then have an action happen, and check the resulting state.

```GDScript
func test_pause() -> void:
    var input = InputManager.new()
    var machine = StateMachine.new(input)
    machine.set_state(State.Active)
    input.pause()
    asserts.is_equal(machine.get_state(), State.PAUSED)
```

Does this help at all?

**Comment by FeralBytes** [comment]
Thank you.
