### ISSUE TITLE
GUI error?

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [AlexDarigan/WAT-GDScript#209]
Hello, I want to use WAT in my project but I have problems using the GUI.
![WAT_GUI_Empty](https://user-images.githubusercontent.com/44974422/116379694-8f7b4e80-a813-11eb-851c-985dcd365802.png)
As you can see on the screenshot I can manually select a test. When I run a test it generates a json file with the result of the test.
Though, I can't see the result in Godot, the Tests tab in the editor remains empty.

I tried it on my project and on your master branch. I have the same problem with both (Using your master branch the output prints this error though, `/gui.gd:32 - Invalid call. Nonexistent function 'clear' in base 'TabContainer (result_forest.gd)'`)

I'm using Godot 3.2.3.stable.fedora.

**Comment by AlexDarigan** [comment]
This might be related to the GUI typo where gui.gd should be GUI.gd

Should be fixed in future versions.
