### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Jummit** [AlexDarigan/WAT-GDScript#225]
I noticed that WAT didn't have a distinct logo, so I designed one:

![path91049](https://user-images.githubusercontent.com/28286961/120926594-d7787580-c6dd-11eb-8c56-fcda6c036544.png)

It's a spin on "Waiting And Testing"; a clock with the hands being a "Test passed" checkmark.

Here are some earlier prototypes:

![image](https://user-images.githubusercontent.com/28286961/120926618-faa32500-c6dd-11eb-8f11-59a38f015505.png)

What do you think?

**Comment by AlexDarigan** [comment]
A new more defined logo would be great and I do love the conceit of this one. I'm going ask around for some feedback before I make a final decision on it.

**Comment by Jummit** [comment]
I made a new version which aims to have better contrast and be better distinguishable when it's very small:

![path97935](https://user-images.githubusercontent.com/28286961/120928928-08a97380-c6e7-11eb-9d5b-4426464ba77c.png)

**Comment by AlexDarigan** [comment]
I'll let you know for sure tomorrow but all signs point to yes. I just don't want to be hasty.

**Comment by Jummit** [comment]
Ok, these are my final designs. Which one of these three is your favorite?

![image](https://user-images.githubusercontent.com/28286961/121040175-fd6f4a00-c7b1-11eb-84bb-98e41193aea2.png)

**Comment by AlexDarigan** [comment]
The center!

**Comment by AlexDarigan** [comment]
Also if it isn't clear I'm considering this the official logo as of now.
